main/urls.py
from django.conf.urls import patterns, url, include
from django.utils.translation import ugettext as _
from main.admin import dashboard
from main.views import PersonCreateView, PersonListView, PersonDetailView, PersonUpdateView, MinuteListView, \
    MinuteCreateView, MinuteUpdateView, MinuteDetailView, MonthBirthdayReportView, GroupCreateView, GroupListView, \
    GroupDetailView, GroupUpdateView

urlpatterns = patterns('',
    url(_(r'^/person$'), PersonListView.as_view(admin_site=dashboard), name="main_person"),
    url(_(r'^/person/add$'), PersonCreateView.as_view(admin_site=dashboard), name="main_person_add"),
    url(_(r'^/person/(?P<pk>[0-9]+)'), include([
        url(_(r'[/]$'), PersonDetailView.as_view(admin_site=dashboard), name="main_person_detail"),
        url(_(r'/edit$'), PersonUpdateView.as_view(admin_site=dashboard), name="main_person_edit"),
    ])),
    url(_(r'^/minute$'), MinuteListView.as_view(admin_site=dashboard), name="main_minute"),
    url(_(r'^/minute/add$'), MinuteCreateView.as_view(admin_site=dashboard), name="main_minute_add"),
    url(_(r'^/minute/(?P<pk>[0-9]+)'), include([
        url(_(r'[/]$'), MinuteDetailView.as_view(admin_site=dashboard), name="main_minute_detail"),
        url(_(r'/edit$'), MinuteUpdateView.as_view(admin_site=dashboard), name="main_minute_edit"),
    ])),
    url(_(r'^/cells$'), GroupListView.as_view(admin_site=dashboard, group_type="cell"), name="main_cell"),
    url(_(r'^/cells/add$'), GroupCreateView.as_view(admin_site=dashboard, group_type="cell"), name="main_cell_add"),
    url(_(r'^/cells/(?P<pk>[0-9]+)'), include([
        url(_(r'[/]$'), GroupDetailView.as_view(admin_site=dashboard, group_type="cell"), name="main_cell_detail"),
        url(_(r'/edit$'), GroupUpdateView.as_view(admin_site=dashboard, group_type="cell"), name="main_cell_edit"),
    ])),
)

petros/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from dashboard_view.views import LoginView, LogoutView
from main.admin import dashboard

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),

    url(r'^dashboard/', include(dashboard.urls)),

    #url(r'^dashboard/$', PetrosDashboardOverviewView.as_view(), name="dashboard_overview"),
    #url(r'^dashboard/profile/$', PetrosDashboardProfileView.as_view(), name="dashboard_profile"),

    url(r'^login$', LoginView.as_view(), name='login'),
    url(r'^logout$', LogoutView.as_view(), name='logout'),

    url(r'^', include('crop_image.urls')),
    #url(r'^dashboard_utils/', include('dashboard_view.urls')),

    url(r'^main', include('main.urls')),

    url(r'^tinymce/', include('tinymce.urls')),

    url(r'^select2/', include('django_select2.urls')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
# coding=utf-8
import os
from django.conf import settings
from django.contrib.auth.models import User
from django.core.files.storage import default_storage
from django.core.urlresolvers import reverse
from django.core.validators import RegexValidator
from django.db import models
from django.utils.translation import ugettext as _
from localflavor.br.br_states import STATE_CHOICES
from localflavor.br.models import BRStateField
from sorl.thumbnail.shortcuts import get_thumbnail
from tinymce.models import HTMLField
from crop_image.forms import CropImageModelField


class Neighborhood(models.Model):
    name = models.CharField(max_length=200)
    city = models.CharField(max_length=200)
    state = BRStateField()
    active = models.BooleanField(default=False)

    def __unicode__(self):
        return u"{0}, {1}, {2}".format(self.name, self.city, self.state, )



class ChurchAccount(models.Model):
    name = models.CharField(max_length=255, verbose_name=_('Name'))
    cnpj = models.CharField(max_length=20, verbose_name='CNPJ', blank=True)
    email = models.EmailField(blank=True, null=True, max_length='200')
    address_line = models.CharField(blank=True, null=True, max_length='300', verbose_name = 'Endereço', validators=[RegexValidator(u'^[\'a-zA-ZáàâãéèêíïóôõöúçñÁÀÂÃÉÈÍÏÓÔÕÖÚÇÑ0-9,\.\s]+$', _(u'Special char not permitted.'))])
    neighborhood = models.CharField(blank=True, null=True,  max_length='200', verbose_name = 'Bairro', validators=[RegexValidator(u'^[\'a-zA-Z0-9áàâãéèêíïóôõöúçñÁÀÂÃÉÈÍÏÓÔÕÖÚÇÑ\s]+$', _(u'Special char not permitted.'))])
    city = models.CharField(blank=True, null=True,  max_length='200', verbose_name = 'Cidade', validators=[RegexValidator(u'^[\'a-zA-ZáàâãéèêíïóôõöúçñÁÀÂÃÉÈÍÏÓÔÕÖÚÇÑ0-9\s]+$', _(u'Special char not permitted.'))])
    state = models.CharField(blank=True, null=True,  max_length='2', verbose_name = 'UF',choices=STATE_CHOICES)
    phone1 = models.CharField(blank=True, max_length=15, verbose_name=_('Phone')+' 1')
    phone2 = models.CharField(blank=True, max_length=15, verbose_name=_('Phone')+' 2')
    logo = CropImageModelField(upload_to="church_logos", null=True, blank=True)

    user_admin = models.ForeignKey(User, related_name="church_user_admin")

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = _("Church Account")

class ChuchAccountSettings(models.Model):
    account = models.OneToOneField(ChurchAccount)


class AccountedManager(models.Manager):
    pass

class AccountedModel(models.Model):
    church_account = models.ForeignKey(ChurchAccount, editable=False)
    added = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    accounted = AccountedManager()

    class Meta:
        abstract = True


class ChurchType(models.Model):
    name = models.CharField(max_length=255)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = _('Church Type')

# Create your models here.
class Church(AccountedModel):
    name = models.CharField(max_length=255, verbose_name=_('Name'))
    cnpj = models.CharField(max_length=20, verbose_name='CNPJ', blank=True)
    email = models.EmailField(blank=True, null=True, max_length='200')
    address_line = models.CharField(blank=True, null=True, max_length='300', verbose_name = 'Endereço', validators=[RegexValidator(u'^[\'a-zA-ZáàâãéèêíïóôõöúçñÁÀÂÃÉÈÍÏÓÔÕÖÚÇÑ0-9,\.\s]+$', _(u'Special char not permitted.'))])
    neighborhood = models.CharField(blank=True, null=True,  max_length='200', verbose_name = 'Bairro', validators=[RegexValidator(u'^[\'a-zA-Z0-9áàâãéèêíïóôõöúçñÁÀÂÃÉÈÍÏÓÔÕÖÚÇÑ\s]+$', _(u'Special char not permitted.'))])
    city = models.CharField(blank=True, null=True,  max_length='200', verbose_name = 'Cidade', validators=[RegexValidator(u'^[\'a-zA-ZáàâãéèêíïóôõöúçñÁÀÂÃÉÈÍÏÓÔÕÖÚÇÑ0-9\s]+$', _(u'Special char not permitted.'))])
    state = models.CharField(blank=True, null=True,  max_length='2', verbose_name = 'UF',choices=STATE_CHOICES)
    phone1 = models.CharField(blank=True, max_length=15, verbose_name=_('Phone')+' 1')
    phone2 = models.CharField(blank=True, max_length=15, verbose_name=_('Phone')+' 2')
    type = models.ForeignKey(ChurchType, blank=True, null=True)
    is_mother = models.BooleanField(default=True)
    church_mother = models.ForeignKey('self', null=True, blank=True, related_name="mother")
    logo = CropImageModelField(upload_to="church_logos", null=True, blank=True)

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('church_detail', (), {'pk': self.id})

    class Meta:
        verbose_name = _('Church')


class MemberFunction(AccountedModel):

    def __str__(self):
        return self.name.encode('utf8')

    title = models.CharField(max_length=60, verbose_name='Título abrev.', help_text='Ex: Dc')
    name = models.CharField(max_length=255, verbose_name='Título', help_text='Ex: Diácono')
    title_female = models.CharField(max_length=60, verbose_name='Título abrev. Feminino', help_text = 'Ex: Dcª')
    name_female = models.CharField(max_length=255, verbose_name='Título Feminino', help_text = 'Ex: Diaconisa')

    class Meta:
        verbose_name = 'Função de membro'
        verbose_name_plural = 'Funções de membro'

class UserPreferences(models.Model):
    language = models.CharField(max_length=10, choices=(
        ('pt-br', 'Português'),
        ('en', 'English'),
    ), default='pt-br', verbose_name=_('Language'))
    user = models.OneToOneField(User, related_name='preferences')

    def __unicode__(self):
        return "%s's preferences" % self.user.get_short_name()

    def get_absolute_url(self):
        return reverse('dashboard:user_preferences')

    class Meta:
        verbose_name = _('User Preference')

class UserProfile(AccountedModel):
    SITUATION_CHOICES = [('A', _('Active')), ('I', _('Inactive'))]

    user = models.OneToOneField(User)

    photo = CropImageModelField(upload_to='user_photos', blank=True, null=True)

    type = models.CharField(max_length=100, choices=(
        #translation: Gathered: Congregado
        ('G', _('Gathered')),
        ('M', _('Member')),
    ))

    cpf = models.CharField(max_length=14, verbose_name='CPF', null=True, blank=True)
    rg = models.CharField(max_length=14, blank=True, null=True, verbose_name='RG')

    birth_date = models.DateField(verbose_name=_('Birth Date'), null=True, blank=True)
    gender = models.CharField(max_length='1', verbose_name=_('Gender'), choices=[('M', _('Male')), ('F', _('Female'))])
    blood_type = models.CharField(max_length='2', blank=True, null=True, verbose_name=_('Blood Type'), choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-','B-'), ('O+', 'O+'), ('O-', 'O-')])

    address_line = models.CharField(blank=True, max_length='300', verbose_name=_('Address'), validators=[RegexValidator(u'^[\'a-zA-ZáàâãéèêíïóôõöúçñÁÀÂÃÉÈÍÏÓÔÕÖÚÇÑ0-9,\.\s]+$', _(u'Special char not permitted.'))])
    neighborhood = models.CharField(blank=True, max_length='200', verbose_name=_('Neighborhood'), validators=[RegexValidator(u'^[\'a-zA-Z0-9áàâãéèêíïóôõöúçñÁÀÂÃÉÈÍÏÓÔÕÖÚÇÑ\s]+$', _(u'Special char not permitted.'))])
    city = models.CharField(blank=True, max_length='200', verbose_name=_('City'), validators=[RegexValidator(u'^[\'a-zA-ZáàâãéèêíïóôõöúçñÁÀÂÃÉÈÍÏÓÔÕÖÚÇÑ0-9\s]+$', _(u'Special char not permitted.'))])
    state = BRStateField(blank=True, null=True)
    zipcode = models.CharField(blank=True, null=True, max_length='10', )
    phone1 = models.CharField(blank=True, max_length='15', verbose_name='Telefone 1',)
    phone2 = models.CharField(blank=True, max_length='15', verbose_name='Telefone 2',)

    profession = models.CharField(blank=True, null=True, max_length='200', verbose_name=_('Profession'))
    work_place = models.CharField(blank=True, null=True, max_length='200', verbose_name=_('Work place'))

    father_name = models.CharField(max_length='255', blank=True, null=True, verbose_name=_('Father name'))
    mother_name = models.CharField(max_length='255', blank=True, null=True, verbose_name=_('Mother name'))
    marital_status = models.CharField(max_length='1', blank=True, null=True, choices=[('S', _('Single')), ('D', _('Divorced')), ('M', _('Married')), ('W', _('Widow')), ])
    spouse = models.CharField(max_length='255', blank=True, null=True, verbose_name=_('Spouse'))
    has_child = models.CharField(blank=True, null=True, max_length='1', verbose_name=_('Has Child?'), choices=[('Y', _('Yes')), ('N', _('No'))])
    how_many_child = models.PositiveSmallIntegerField(default=0, blank=True, null=True)

    previous_church = models.CharField(max_length='255', blank=True, null=True, verbose_name=_('Previous church'))
    previous_function = models.CharField(max_length='255', blank=True, null=True, verbose_name=_('Previous function'))
    baptism_date = models.DateField(verbose_name=_('Baptism date'), blank=True, null=True)
    baptism_place = models.CharField(max_length='255', blank=True, null=True, verbose_name=_('Baptism place'))
    admission_date = models.DateField(blank=True, null=True, verbose_name=_('Admission date'))
    member_function = models.ForeignKey(MemberFunction, blank=True, null=True, verbose_name=_("Member Function"))

    situation = models.CharField(max_length=7, verbose_name=_("Situation"), choices=SITUATION_CHOICES, default='A')
    church = models.ForeignKey(Church)

    discipler = models.ForeignKey('self', related_name=_("discipler_user"), null=True, blank=True, verbose_name=_("Discipler"))


    #TODO: Spouse - Foreign Key
    #TODO: Children - ManyToManyField or Foreing Key in a ChildrenObject

    def __unicode__(self):
        return self.user.get_full_name()

    def get_absolute_url(self):
        return reverse('main_person_detail', kwargs={'pk': self.pk})

    def get_thumbnail(self):
        if self.photo:
            return settings.MEDIA_URL + self.photo.path
        else:
            if self.gender == 'F':

main/templates/main/minute_detail.html
{% extends 'generics/dashboard_detail.html' %}
{% load i18n %}
{% load staticfiles %}

{% block detail %}
    {% block message %}
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{% if message.tags %}{{ message.tags }} alert-dismissible"{% endif %}>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                {{ message }}
            </div>
            {% endfor %}
        {% endif %}
    {% endblock %}

    <h1>{{ object.title }}<small> - {{ object.category }}</small></h1>
    <h2><small>{{ object.date }}</small></h2>
    <br>
    {{ object.content|safe }}
{%  endblock %}

main/templates/main/userprofile_detail.html
{% extends 'generics/dashboard_detail.html' %}
{% load i18n %}
{% load staticfiles %}

{% block detail %}
    
    <div class="panel">
        <div class="panel-body">
            {% csrf_token %}
{#            {{ form_user|as_bootstrap}}#}
                <div class="col-xs-4 col-lg-2">
                    <img src="{{ object.get_thumbnail }}" class="img-thumbnail img-responsive">
                </div>
                <div class="col-xs-8 col-lg-10">
                    <h2>{{ object.user.get_full_name }}<br>
                        <small>{{ object.get_type_display }} {% if object.member_function %} | {{ object.get_member_function_display }}{% endif %}</small>
                    </h2>
                    <p><strong>Email:</strong> {{ object.user.email }}</p>
                    <p><strong>{% trans "Username" %}</strong>: {{ object.user.username }}</p>
                </div>


{#            {% buttons %}#}
        </div>
    </div>
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active"><a href="#personal" aria-controls="personal" role="tab" data-toggle="tab">
            {% trans 'Personal' %} {% if form_personal.errors %}<span class="text-danger fa fa-exclamation-triangle"></span>{% endif %}
        </a></li>
        <li role="presentation"><a href="#contact" aria-controls="contact" role="tab" data-toggle="tab">
            {% trans 'Contact' %}  {% if form_contact.errors %}<span class="text-danger fa fa-exclamation-triangle"></span>{% endif %}
        </a></li>
        <li role="presentation"><a href="#ecclesiastic" aria-controls="ecclesiastic" role="tab" data-toggle="tab">
            {% trans 'Ecclesiastic' %}  {% if form_ecclesiastic.errors %}<span class="text-danger fa fa-exclamation-triangle"></span>{% endif %}
        </a></li>
    </ul>

        <div class="tab-content">
            <div role="tabpanel" class="tab-pane active" id="personal">
                <div class="panel-body">
                    <p><strong>{% trans "Birth date" %}</strong> {{ object.birth_date }} </p>
                    {% if object.rg %}<p><strong>{% trans "RG" %}</strong> {{ object.rg }} </p>{% endif %}
                    <p><strong>{% trans "CPF" %}</strong> {{ object.cpf }} </p>
                    <p><strong>{% trans "Gender" %}</strong> {{ object.get_gender_display }} </p>
                    {% if object.marital_status %}<p><strong>{% trans "Marital status" %}</strong> {{ object.get_marital_status_display }} </p>{% endif %}
                    {% if object.father_name %}<p><strong>{% trans "Father name" %}</strong> {{ object.father_name }} </p>{% endif %}
                    {% if object.mother_name %}<p><strong>{% trans "Mother name" %}</strong> {{ object.mother_name }} </p>{% endif %}
                    {% if object.spouse %}<p><strong>{% trans "Spouse" %}</strong> {{ object.spouse }} </p>{% endif %}
                    {% if object.blood_type %}<p><strong>{% trans "Blood Type" %}</strong> {{ object.get_blood_type_display }} </p>{% endif %}
                    {% if object.has_child %}<p><strong>{% trans "Has Child?" %}</strong> {{ object.get_has_child_display }} </p>{% endif %}
                    {% if object.how_many_child %}<p><strong>{% trans "How many child?" %}</strong> {{ object.how_many_child }} </p>{% endif %}
                </div>
            </div>
            <div role="tabpanel" class="tab-pane" id="contact">
                 <div class="panel-body">
                    {% if object.address_line %}<p><strong>{% trans "Address" %} </strong>: {{ object.address_line }}{% endif %}
                    {% if object.neighborhood %}<p><strong>{% trans "Neighborhood" %}</strong>: {{ object.neighborhood }}{% endif %}
                    {% if object.city %}<p><strong>{% trans "City" %}</strong>: {{ object.city }}{% endif %}
                    {% if object.state %}<p><strong>{% trans "State" %}</strong>: {{ object.state }}{% endif %}
                    {% if object.zipcode %}<p><strong>{% trans "Zipcode" %}</strong>: {{ object.zipcode }}{% endif %}
                    {% if object.phone1 %}<p><strong>{% trans "Phone 1" %}</strong>: {{ object.phone1 }}{% endif %}
                    {% if object.phone2 %}<p><strong>{% trans "Phone 2" %}</strong>: {{ object.phone2 }}{% endif %}
                </div>
            </div>
            <div role="tabpanel" class="tab-pane" id="ecclesiastic">
                 <div class="panel-body">
                     <p><strong>{% trans "Type" %}</strong>: {{ object.get_type_display }}
                     {% if object.situation %}<p><strong>{% trans "Situation" %}</strong>: {{ object.get_situation_display }}{% endif %}
                     {% if object.previous_church %}<p><strong>{% trans "Previous church" %}</strong>: {{ object.previous_church }}{% endif %}
                     {% if object.previous_function %}<p><strong>{% trans "Previous function" %}</strong>: {{ object.previous_function }}{% endif %}
                     {% if object.baptism_date %}<p><strong>{% trans "Bapstism date" %}</strong>: {{ object.baptism_date }}{% endif %}
                     {% if object.baptism_place %}<p><strong>{% trans "Baptism place" %}</strong>: {{ object.baptism_place }}{% endif %}
                     {% if object.admission_date %}<p><strong>{% trans "Admission date" %}</strong>: {{ object.admission_date }}{% endif %}
                     {% if object.member_function %}<p><strong>{% trans "Member Function" %}</strong>: {{ object.member_function }}{% endif %}
                     {% if object.church %}<p><strong>{% trans "Church" %}</strong>: {{ object.church }}{% endif %}
                     {% if object.discipler %}<p><strong>{% trans "Discipler" %}</strong>: {{ object.discipler }}{% endif %}
                </div>
            </div>
        </div>
{%  endblock %}

main/templates/main/userprofile_form.html
{% extends "generics/dashboard_form.html" %}
{% load i18n %}
{% load bootstrap_form %}
{% load staticfiles %}

{% block form %}
    {% if form_basic.errors or form_user.errors or form_personal.errors or form_contact.errors or form_ecclesiastic.errors %}
        <div class="alert alert-danger alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          Existem alguns campos que são obrigatórios. <br>Verifique as abas marcas com <span class="fa fa-exclamation-triangle"></span>
        </div>
    {% endif %}
    <form class="form-horizontal" method="POST" enctype="multipart/form-data">
        <div class="panel">
            <div class="panel-body">
                {% csrf_token %}
                {{ form_user|as_bootstrap}}

                {% if object %}
                <div class="form-group form-group-sm">
                    <label class="col-sm-3 col-lg-2 control-label">{% trans 'Password' %}</label>
                    <div class="col-sm-8 col-lg-4">
                        <span class="help-block"><a href="">{% trans "Change Password" %}</a></span>
                    </div>
                </div>
                {% endif %}
                {% buttons %}
            </div>
        </div>
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active"><a href="#user" aria-controls="user" role="tab" data-toggle="tab">
            {% trans 'Photo' %} {% if form_basic.errors %}<span class="text-danger fa fa-exclamation-triangle"></span>{% endif %}
        </a></li>
        <li role="presentation"><a href="#personal" aria-controls="personal" role="tab" data-toggle="tab">
            {% trans 'Personal' %} {% if form_personal.errors %}<span class="text-danger fa fa-exclamation-triangle"></span>{% endif %}
        </a></li>
        <li role="presentation"><a href="#contact" aria-controls="contact" role="tab" data-toggle="tab">
            {% trans 'Contact' %}  {% if form_contact.errors %}<span class="text-danger fa fa-exclamation-triangle"></span>{% endif %}
        </a></li>
        <li role="presentation"><a href="#ecclesiastic" aria-controls="contact" role="tab" data-toggle="tab">
            {% trans 'Ecclesiastic' %}  {% if form_ecclesiastic.errors %}<span class="text-danger fa fa-exclamation-triangle"></span>{% endif %}
        </a></li>
    </ul>

        <div class="tab-content">
            <div role="tabpanel" class="tab-pane active" id="user">
                <div class="panel-body">
                        {{ form_basic|as_bootstrap}}
                        {% buttons %}
                </div>
            </div>
            <div role="tabpanel" class="tab-pane" id="personal">
                 <div class="panel-body">
                        {{ form_personal|as_bootstrap}}
                        {% buttons %}
                </div>
            </div>
            <div role="tabpanel" class="tab-pane" id="contact">
                 <div class="panel-body">
                        {{ form_contact|as_bootstrap}}
                        {% buttons %}
                </div>
            </div>
            <div role="tabpanel" class="tab-pane" id="ecclesiastic">
                 <div class="panel-body">
                        {{ form_ecclesiastic|as_bootstrap}}
                        {% buttons %}
                </div>
            </div>
        </div>
    </form>
{% endblock %}

{% block extra_footer_scripts %}
    {{ form_user.media }}
    {{ form_contact.media }}
    {{ form_personal.media }}
    {{ form_ecclesiastic.media }}
{% endblock %}